# this is the front end for atlas softer pinko docker
FROM nginx:latest
COPY ./softy-pinko-front-end /usr/www/html/softy-pinko-front-end
COPY ./softy-pinko-front-end.conf /etc/nginx/conf.d/default.conf
EXPOSE 9000
